name = "marketdata-docusaurus-proxy"
main = "index.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "www-staging.marketdata.app/docs", zone_name = "marketdata.app" },
  { pattern = "www-staging.marketdata.app/docs/*", zone_name = "marketdata.app" },
  { pattern = "www.marketdata.app/docs", zone_name = "marketdata.app" },
  { pattern = "www.marketdata.app/docs/*", zone_name = "marketdata.app" },
]

[observability]
enabled = true
head_sampling_rate = 1
